In [1]:
import tensorflow as tf

print(tf.__version__)

2.2.0-dev20200315


# Basics of Tensorflow 2.0

In [10]:
# 1. Creat a constant/scalar, vector, matrix
a = tf.constant(1.2)
aa = tf.constant ([2,3])
aaa = tf.constant([[1,2],[3,4]])
print(a,aa,aaa)
# String will be used as a constant of string
b = tf.constant('This is a string!')
print(b)
# tf.strings provides some 
tf.strings.lower(b)
# Boolean type
c = tf.constant(True)
cc = tf.constant(False)
print(c,cc)

tf.Tensor(1.2, shape=(), dtype=float32) tf.Tensor([2 3], shape=(2,), dtype=int32) tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(b'This is a string!', shape=(), dtype=string)
tf.Tensor(True, shape=(), dtype=bool) tf.Tensor(False, shape=(), dtype=bool)


In [18]:
# 2. Precision
import numpy as np
a = tf.constant(123,dtype=tf.int16)
b = tf.constant(123,dtype=tf.int32)
c = tf.constant(np.pi,dtype=tf.float32)
d = tf.constant(np.pi,dtype=tf.float64)
# to read the precision of a variable/tensor, use xxx.dtype (xxx is the name of the tensor)
print("data type: ",a.dtype)
# use tf.cast to convert the data type: new_tensor = tf.cast(xxx, new_type)
if a.dtype!=tf.float32:
    a = tf.cast(a, tf.float32)
print("data type: ",a.dtype)

data type:  <dtype: 'int16'>
data type:  <dtype: 'float32'>


In [54]:
# 3. Create a tensor
# 3.1 Create a tensor from an existing data object
tf.convert_to_tensor([1.0, 2.0], dtype=tf.float16)
tf.convert_to_tensor(np.array([3,4]), dtype=tf.float32)
# 3.2 Create all ones/zeros tensor
a = tf.ones([2,2])
b = tf.zeros([3,3])
# use tf.zeros_like/ones_like to create all ones/zeros tensor with the same shape as the input
aa = tf.zeros_like(a)
bb = tf.ones_like(b)
print(a,aa)
print(b,bb)
# use tf.fill(shape, value) to create a tensor with all pre-defined values
c = tf.fill([4,4],4)
print(c)
# 3.3 Create a tensor with distributions.
# Use tf.random.normal(shape, mean, stddev) to create a tensor with a normal distribution
d = tf.random.normal([5,6], mean=1.0, stddev=1.0)
print(d)
e = tf.random.uniform([6,6], minval=10, maxval=20, dtype=tf.float32)
print(e)
# 3.4 Create a list with tf.range(limit, delta/step), begin with 0 by default
f = tf.range(10)
ff = tf.range(10,delta=2)
fff = tf.range(-10,10, 2)
print(f,ff,fff)
# 3.5 Indexing and Slicing
x = tf.random.normal([4,28,28,3])
print(x[0])
print(x[:2])
# 3.6 Reshape: tf.reshape(x, new_shape)
xx = tf.reshape(x,[4,-1,3])
xxx = tf.reshape(x,[-1,3])
print(xx,xxx)
# 3.7 Adding or Removing dimension
y = tf.random.normal([28,28])
print(y)
y = tf.expand_dims(y,-1)
print(y)
y = tf.expand_dims(y,0)
print(y)
# use tf.squeeze(x, axis) to delete a dimension
y = tf.squeeze(y,0)
print(y)
y = tf.squeeze(y,-1)
print(y)
# 3.8 Dimension swapping
x = tf.random.normal([2, 32, 28,2])
x = tf.transpose(x, [0,3,1,2])
print(x)
x = tf.transpose(x,[0,1,3,2])
print(x)
# 3.9 Clone data and Broadcasting
# use tf.tile(x, multiples) to clone data
y = tf.tile(y,[1,2])
print(y)
# as explicitly copying data is very expensive, it is more frequently to use broadcasting instead
# Broadcasting will align the smaller tensor in the right and add in more dimension as requested.
x = tf.random.normal([32,1])
# to convert x into a four dimension [1,32,32,1]
x = tf.broadcast_to(x,[1,32,32,1])
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]], shape=(4, 4), dtype=int32)
tf.Tensor(
[[ 0.5716946   0.76299715  1.2245532  -0.78652024  0.94673824  1.0926371 ]
 [ 0.86890644  0.51323885  1.3273681   0.6097655   0.38830018  0.871198  ]
 [ 0.3138783   0.77326095  0.48079473  2.0163043  -0.3004346   0.17604369]
 [ 1.43235     0.53451484 -0.76661766  2.7743673  -0.34985554  0.20083427]
 [ 0.1323635   2.1564407   0.56003547  1.1670518   1.553808    1.2097716 ]], shape=(5, 6), dtype=float32)
tf.Tensor(
[[10.630617  16.240713  11.282534  10.972978  19.9045    15.474541 ]
 [15.929726  16.379814  15.373946  15.497505  14.422699  19.666977 ]
 [13.710795  14.442106  14.224524  14.419926  13.210668  17.1946   ]
 [12.

# Advanced Topics of Tensorflow 2.0